version: "3"

services:
    app:
        build: .
        container_name: http-go
        volumes:
            - .:/go/src
        extra_hosts: 
            - "host.docker.interval:172.17.0.1"
        ports:
            - 8000:8000